import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UtilService {
  constructor() {}

  /**
   * @param - A product
   * @returns - It returns Id generated by {key}, {specialRequest}, {ingredient.extraName}
   */
  generateProductIdForCart(product: Record<string, any>): string {
    let idForCart = product.key + '-' + product.specialRequest + '-';
    if (product.ingredient) {
      const includedIngredients = product.ingredient.filter((e) => e.include);
      if (includedIngredients.length) {
        idForCart += includedIngredients
          .map((e) => e.extraName ?? '')
          .join('-')
          .replace(/\s+/g, '');
      }
    }
    return idForCart;
  }
}
